"""updated users table added is author

Revision ID: 68e0a8e5a8a1
Revises: 736efcc27f77
Create Date: 2026-07-01 06:24:45.102700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e0a8e5a8a1'
down_revision = '736efcc27f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cook_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cook_steps_created_at'), ['created_at'], unique=False)

    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tips_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_author', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_author')

    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tips_created_at'))

    op.drop_table('tips')
    with op.batch_alter_table('cook_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cook_steps_created_at'))

    op.drop_table('cook_steps')
    # ### end Alembic commands ###
