"""updated comments table with author id

Revision ID: 736efcc27f77
Revises: daa7559bad42
Create Date: 2026-06-19 06:46:06.198997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736efcc27f77'
down_revision = 'daa7559bad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_author_id_users', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_author_id_users', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
