"""updated cook_steps table and tips table

Revision ID: f1ce0a01744d
Revises: 7087c9f8a6ea
Create Date: 2026-07-02 06:43:48.203118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ce0a01744d'
down_revision = '7087c9f8a6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1024), nullable=False))
        batch_op.create_foreign_key('fk_cook_steps_recipe_id_recipes', 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_step_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1024), nullable=False))
        batch_op.create_foreign_key('fk_tips_cook_step_id_cook_steps', 'cook_steps', ['cook_step_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tips_cook_step_id_cook_steps', type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('cook_step_id')

    with op.batch_alter_table('cook_steps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cook_steps_recipe_id_recipes', type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('sequence')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
